# Generated by Django 2.1.7 on 2019-03-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='assignment',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='assignment',
            new_name='student',
        ),
    ]
