# Generated by Django 2.1.7 on 2019-03-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0003_auto_20190309_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='Schedule_App.My_Student'),
        ),
    ]
