# Generated by Django 2.1.7 on 2019-03-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0004_auto_20190309_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='Schedule_App.My_Student'),
        ),
    ]
