# Generated by Django 2.1.7 on 2019-03-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0005_auto_20190311_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='dt_of_booking',
            new_name='date_of_booking',
        ),
        migrations.AlterField(
            model_name='my_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relation', to='Schedule_App.Student'),
        ),
        migrations.AlterField(
            model_name='my_student',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_relation', to='Schedule_App.Tutor'),
        ),
    ]
