# Generated by Django 2.1.7 on 2019-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0006_auto_20190311_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Tutor', 'Tutor'), ('Student', 'Student'), ('Guest', 'Guest')], default='Guest', max_length=10),
        ),
    ]
