# Generated by Django 2.1.7 on 2019-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0010_auto_20190312_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pic.png', upload_to=''),
        ),
    ]
