# Generated by Django 2.1.7 on 2019-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0011_auto_20190312_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile_pic.png', upload_to=''),
        ),
    ]
