# Generated by Django 2.1.7 on 2019-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0013_auto_20190312_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
