# Generated by Django 2.1.7 on 2019-03-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0016_auto_20190312_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='profile_pic',
        ),
    ]
