# Generated by Django 2.1.7 on 2019-03-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule_App', '0017_auto_20190313_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('schedule', 'assignment')},
        ),
    ]
